name: ludonew
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  get: ^4.7.2
  just_audio: 
  otp_text_field: ^1.1.3
  provider: ^6.1.2
  simple_ripple_animation: ^0.0.9
  flame_audio: ^2.10.7
  flame: ^1.23.0
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_database: ^11.3.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png" 
  android: true
  ios: true  
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/dice/
    - assets/images/crown/
    - assets/sounds/
    - assets/audio/move.mp3
    - assets/audio/dice.mp3
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Bold.ttf
